project:
  type: website

website:
  title: "Grandez"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: wsl.qmd
        text: WSL
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
    grid:
      sidebar-width: 150px
      body-width: 1200px
      margin-width: 150px
      gutter-width: 1.5rem
editor: source

