project:
  type: website

website:
  title: "Las ciegas hormigas electricas (2)"
  page-navigation: true
  navbar:
    background: light
    logo: images/buho.png
    logo-alt: "Serendipias"
    title: false
    collapse-below: lg  
    search: false
    left:
      - href: index.qmd
        text: Home
      - href: docs/quarto/quarto.qmd
        text: Quarto
      - href: docs/bookdown/bookdown.qmd
        text: Bookdown
      - href: docs/poc/virtual.qmd
        text: QuasiVirtual
      - href: about.qmd
        text: About
  sidebar:
    - id: poc
      title: "WSL"
      style: "docked"
      pinned: true
      collapse-level: 2
      align: left
      contents:
        - section: "Poc"
          contents:
            - text: "Vision general"
              href: docs/poc/poc.qmd
            - text: "Windows"
              href: docs/poc/windows.qmd
            - text: "WSL"
              href: docs/poc/wsl.qmd
            - text: "Tutorial: Authoring"
              href: docs/get-started/authoring/

format:
  html:
    toc: false
    page-layout: full
    code-line-numbers: true
    grid:
      sidebar-width: 150px
      body-width: 1200px
      margin-width: 150px
      gutter-width: 1.5rem
      
editor: source

